version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql-nesm
    environment:
      MYSQL_ROOT_PASSWORD: nesm
      MYSQL_DATABASE: bd_nesm
      MYSQL_ROOT_PASSWORD: root_nesm
      MYSQL_USER: nesm_user
      MYSQL_PASSWORD: nesm_pass
    command: mysqld --user=root --verbose
    volumes:
      - ./mysql/script:/docker-entrypoint-initdb.d/
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    restart: always
    ports:
      - 3306:3306
  web:
    build: node/
    volumes:
      - ./node/app/:/usr/src/app
    ports:
      - "8080:3000"
    links:
      - mysql
  



  