version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql-weeder
    environment:
      MYSQL_ROOT_PASSWORD: weeder
      MYSQL_DATABASE: bd_weeder
      MYSQL_ROOT_PASSWORD: root_weeder
      MYSQL_USER: weeder_user
      MYSQL_PASSWORD: weeder_pass
    command: mysqld --user=root --verbose
    volumes:
      - ./mysql/script:/docker-entrypoint-initdb.d/
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    restart: always
    ports:
      - 3306:3306
  web:
    build: node/
    ports:
      - "8080:80"
    links:
      - mysql
volumes:
  node:
  



  