###Obtener todos
GET http://localhost:8080/todos HTTP/1.1

###Obtener por id
GET http://localhost:8080/todos/1 HTTP/1.1

### Crear nuevo todo
POST http://localhost:8080/todos HTTP/1.1
content-type: application/json

{
    "title": "ejemplo1",
    "description": "descripcion ejemplo"
}

### Actualizar Todo
PUT http://localhost:8080/todos/1 HTTP/1.1
content-type: application/json

{
    "title": "ejemplo3",
    "description": "descripcion ejemplo"
}

### eliminar Todo
DELETE  http://localhost:8080/todos/5 HTTP/1.1
content-type: application/json